import { useState } from 'react';
import Navbar from '../components/Navbar';
import { FileText, Database } from 'lucide-react';

export default function EmployeeDashboard() {
  const [dark, setDark] = useState(true);

  return (
    <div className={`min-h-screen ${dark ? 'bg-black text-white' : 'bg-white text-gray-900'}`}>
      <Navbar dark={dark} toggleDark={() => setDark((d) => !d)} feedActive={true} />

      <main className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-10 space-y-8">
        <section>
          <h1 className="text-3xl font-bold tracking-tight mb-4">
            Employee Dashboard
          </h1>
          <p className="text-gray-400">
            Access and analyze your personal security logs and the company’s shared database insights in real time.
          </p>
        </section>

        {/* Employee Cards */}
        <section className="grid grid-cols-1 md:grid-cols-2 gap-6">
          
          {/* Card 1 - Local Credentials Security Logs */}
          <div className="rounded-2xl border border-gray-800 bg-zinc-900 p-6 shadow-lg hover:shadow-xl transition-shadow duration-300">
            <div className="flex items-center gap-3 mb-4">
              <FileText className="w-6 h-6 text-emerald-500" />
              <h2 className="text-xl font-semibold">Your Credentials & Security Logs</h2>
            </div>
            <p className="text-gray-400 text-sm mb-4">
              View your login patterns, credential access activity, and real-time alerts generated by the monitoring system.
            </p>
            <ul className="list-disc ml-6 text-gray-400 text-sm mb-4 space-y-1">
              <li>Live visualization of your security log data</li>
              <li>Rule-based anomaly detection</li>
              <li>LLM-based recommendations for safer credential use</li>
            </ul>
            <button
              onClick={() => alert('Redirecting to your personal security log dashboard...')}
              className="px-4 py-2 rounded-md bg-emerald-600 hover:bg-emerald-700 text-sm font-medium transition-colors duration-200"
            >
              View My Logs
            </button>
          </div>

          {/* Card 2 - Shared Database Security Insights */}
          <div className="rounded-2xl border border-gray-800 bg-zinc-900 p-6 shadow-lg hover:shadow-xl transition-shadow duration-300">
            <div className="flex items-center gap-3 mb-4">
              <Database className="w-6 h-6 text-amber-500" />
              <h2 className="text-xl font-semibold">Company DB Security Insights</h2>
            </div>
            <p className="text-gray-400 text-sm mb-4">
              Explore global database activity, anomalies, and blockchain-verified integrity of logs shared across departments.
            </p>
            <ul className="list-disc ml-6 text-gray-400 text-sm mb-4 space-y-1">
              <li>Live analytics of shared security events</li>
              <li>Blockchain verification of log integrity</li>
              <li>Automated vulnerability recommendations</li>
            </ul>
            <button
              onClick={() => alert('Redirecting to shared security insights...')}
              className="px-4 py-2 rounded-md bg-amber-600 hover:bg-amber-700 text-sm font-medium transition-colors duration-200"
            >
              View Shared Logs
            </button>
          </div>

        </section>
      </main>
    </div>
  );
}
